# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515432ef8a8c54888d87cb9caf0876092f74a52ba0f5392032871d8e876a85c6d03f1f2c318c7129f436d8e7554ed283ddd08419d13629b4a8533120cb21b5bc

test:
  secret_key_base: 9b3ee04e23ba1abae3512fad2c062b522649b1f46ac5886cd62080a200cb1379f4f52f878c3747c1beac076afaa27389a92a82a4ef2c92fb98ccfe629ce1d973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
